/** Canonical book order matching thiagobodruk/bible JSON arrays (66 books). */
export const BIBLE_BOOK_NAMES = [
  'Genesis',
  'Exodus',
  'Leviticus',
  'Numbers',
  'Deuteronomy',
  'Joshua',
  'Judges',
  'Ruth',
  '1 Samuel',
  '2 Samuel',
  '1 Kings',
  '2 Kings',
  '1 Chronicles',
  '2 Chronicles',
  'Ezra',
  'Nehemiah',
  'Esther',
  'Job',
  'Psalm',
  'Proverbs',
  'Ecclesiastes',
  'Song of Solomon',
  'Isaiah',
  'Jeremiah',
  'Lamentations',
  'Ezekiel',
  'Daniel',
  'Hosea',
  'Joel',
  'Amos',
  'Obadiah',
  'Jonah',
  'Micah',
  'Nahum',
  'Habakkuk',
  'Zephaniah',
  'Haggai',
  'Zechariah',
  'Malachi',
  'Matthew',
  'Mark',
  'Luke',
  'John',
  'Acts',
  'Romans',
  '1 Corinthians',
  '2 Corinthians',
  'Galatians',
  'Ephesians',
  'Philippians',
  'Colossians',
  '1 Thessalonians',
  '2 Thessalonians',
  '1 Timothy',
  '2 Timothy',
  'Titus',
  'Philemon',
  'Hebrews',
  'James',
  '1 Peter',
  '2 Peter',
  '1 John',
  '2 John',
  '3 John',
  'Jude',
  'Revelation',
] as const;

export type BibleBookName = (typeof BIBLE_BOOK_NAMES)[number];

/** Aliases used for spoken / typed reference detection. */
export const bookAliases: Record<string, string[]> = {
  Genesis: ['genesis', 'gen'],
  Exodus: ['exodus', 'exod', 'ex'],
  Leviticus: ['leviticus', 'lev'],
  Numbers: ['numbers', 'num'],
  Deuteronomy: ['deuteronomy', 'deut'],
  Joshua: ['joshua', 'josh'],
  Judges: ['judges', 'judg'],
  Ruth: ['ruth'],
  '1 Samuel': ['1 samuel', 'first samuel', 'i samuel', 'one samuel'],
  '2 Samuel': ['2 samuel', 'second samuel', 'ii samuel', 'two samuel'],
  '1 Kings': ['1 kings', 'first kings', 'i kings', 'one kings'],
  '2 Kings': ['2 kings', 'second kings', 'ii kings', 'two kings'],
  '1 Chronicles': ['1 chronicles', 'first chronicles', 'i chronicles'],
  '2 Chronicles': ['2 chronicles', 'second chronicles', 'ii chronicles'],
  Ezra: ['ezra'],
  Nehemiah: ['nehemiah', 'neh'],
  Esther: ['esther', 'est'],
  Job: ['job'],
  Psalm: ['psalm', 'psalms', 'ps'],
  Proverbs: ['proverbs', 'prov'],
  Ecclesiastes: ['ecclesiastes', 'eccl'],
  'Song of Solomon': ['song of solomon', 'song of songs', 'songs'],
  Isaiah: ['isaiah', 'isa'],
  Jeremiah: ['jeremiah', 'jer'],
  Lamentations: ['lamentations', 'lam'],
  Ezekiel: ['ezekiel', 'ezek'],
  Daniel: ['daniel', 'dan'],
  Hosea: ['hosea', 'hos'],
  Joel: ['joel'],
  Amos: ['amos'],
  Obadiah: ['obadiah', 'obad'],
  Jonah: ['jonah'],
  Micah: ['micah', 'mic'],
  Nahum: ['nahum', 'nah'],
  Habakkuk: ['habakkuk', 'hab'],
  Zephaniah: ['zephaniah', 'zeph'],
  Haggai: ['haggai', 'hag'],
  Zechariah: ['zechariah', 'zech'],
  Malachi: ['malachi', 'mal'],
  Matthew: ['matthew', 'matt'],
  Mark: ['mark'],
  Luke: ['luke'],
  John: ['john', 'jn'],
  Acts: ['acts'],
  Romans: ['romans', 'rom'],
  '1 Corinthians': ['1 corinthians', 'first corinthians', 'one corinthians', 'i corinthians'],
  '2 Corinthians': ['2 corinthians', 'second corinthians', 'two corinthians', 'ii corinthians'],
  Galatians: ['galatians', 'gal'],
  Ephesians: ['ephesians', 'eph'],
  Philippians: ['philippians', 'phil'],
  Colossians: ['colossians', 'col'],
  '1 Thessalonians': ['1 thessalonians', 'first thessalonians', 'i thessalonians'],
  '2 Thessalonians': ['2 thessalonians', 'second thessalonians', 'ii thessalonians'],
  '1 Timothy': ['1 timothy', 'first timothy', 'i timothy'],
  '2 Timothy': ['2 timothy', 'second timothy', 'ii timothy'],
  Titus: ['titus'],
  Philemon: ['philemon', 'phlm'],
  Hebrews: ['hebrews', 'heb'],
  James: ['james', 'jas'],
  '1 Peter': ['1 peter', 'first peter', 'i peter'],
  '2 Peter': ['2 peter', 'second peter', 'ii peter'],
  '1 John': ['1 john', 'first john', 'i john'],
  '2 John': ['2 john', 'second john', 'ii john'],
  '3 John': ['3 john', 'third john', 'iii john'],
  Jude: ['jude'],
  Revelation: ['revelation', 'rev'],
};

export type BibleTranslationSource = 'thiagobodruk' | 'helloao';

export type BibleTranslationEntry = {
  code: string;
  label: string;
  language: string;
  source: BibleTranslationSource;
  file?: string;
  helloaoId?: string;
  /** Lower numbers import earlier on first run. */
  priority?: number;
};

/** English modern translations (HelloAO — free, no API key). */
export const HELLOAO_ENGLISH_TRANSLATIONS: BibleTranslationEntry[] = [
  { code: 'BSB', source: 'helloao', helloaoId: 'BSB', label: 'Berean Standard Bible', language: 'English', priority: 1 },
  { code: 'WEB', source: 'helloao', helloaoId: 'eng_web', label: 'World English Bible', language: 'English', priority: 1 },
  { code: 'WEBP', source: 'helloao', helloaoId: 'ENGWEBP', label: 'World English Bible (Protestant)', language: 'English', priority: 2 },
  { code: 'NET', source: 'helloao', helloaoId: 'eng_net', label: 'NET Bible', language: 'English', priority: 1 },
  { code: 'ASV', source: 'helloao', helloaoId: 'eng_asv', label: 'American Standard Version', language: 'English', priority: 2 },
  { code: 'FBV', source: 'helloao', helloaoId: 'eng_fbv', label: 'Free Bible Version', language: 'English', priority: 2 },
  { code: 'PEV', source: 'helloao', helloaoId: 'eng_pev', label: 'Plain English Version', language: 'English', priority: 2 },
  { code: 'MSB', source: 'helloao', helloaoId: 'eng_msb', label: 'Majority Standard Bible', language: 'English', priority: 3 },
  { code: 'GNV', source: 'helloao', helloaoId: 'eng_gnv', label: 'Geneva Bible 1599', language: 'English', priority: 3 },
  { code: 'YLT', source: 'helloao', helloaoId: 'eng_ylt', label: "Young's Literal Translation", language: 'English', priority: 3 },
  { code: 'DARBY', source: 'helloao', helloaoId: 'eng_dby', label: 'Darby Translation', language: 'English', priority: 3 },
  { code: 'LSV', source: 'helloao', helloaoId: 'eng_lsv', label: 'Literal Standard Version', language: 'English', priority: 3 },
  { code: 'ULB', source: 'helloao', helloaoId: 'eng_ulb', label: 'Unlocked Literal Bible', language: 'English', priority: 3 },
  { code: 'WMB', source: 'helloao', helloaoId: 'eng_wmb', label: 'World Messianic Bible', language: 'English', priority: 3 },
];

/** Full catalog: HelloAO English + thiagobodruk multilingual. */
export const BIBLE_TRANSLATION_CATALOG: BibleTranslationEntry[] = [
  ...HELLOAO_ENGLISH_TRANSLATIONS,
  { code: 'KJV', source: 'thiagobodruk', file: 'en_kjv.json', label: 'King James Version', language: 'English', priority: 1 },
  { code: 'BBE', source: 'thiagobodruk', file: 'en_bbe.json', label: 'Bible in Basic English', language: 'English', priority: 2 },
  { code: 'RVR', source: 'thiagobodruk', file: 'es_rvr.json', label: 'Reina-Valera', language: 'Spanish' },
  { code: 'SCHLACHTER', source: 'thiagobodruk', file: 'de_schlachter.json', label: 'Schlachter', language: 'German' },
  { code: 'GREEK', source: 'thiagobodruk', file: 'el_greek.json', label: 'Modern Greek', language: 'Greek' },
  { code: 'APEE', source: 'thiagobodruk', file: 'fr_apee.json', label: "La Bible de l'Épée", language: 'French' },
  { code: 'AA', source: 'thiagobodruk', file: 'pt_aa.json', label: 'Almeida Revisada', language: 'Portuguese' },
  { code: 'ACF', source: 'thiagobodruk', file: 'pt_acf.json', label: 'Almeida Corrigida Fiel', language: 'Portuguese' },
  { code: 'NVI', source: 'thiagobodruk', file: 'pt_nvi.json', label: 'Nova Versão Internacional (PT)', language: 'Portuguese' },
  { code: 'CUV', source: 'thiagobodruk', file: 'zh_cuv.json', label: 'Chinese Union Version', language: 'Chinese' },
  { code: 'NCV', source: 'thiagobodruk', file: 'zh_ncv.json', label: 'New Chinese Version', language: 'Chinese' },
  { code: 'KO', source: 'thiagobodruk', file: 'ko_ko.json', label: 'Korean Bible', language: 'Korean' },
  { code: 'SYNODAL', source: 'thiagobodruk', file: 'ru_synodal.json', label: 'Russian Synodal', language: 'Russian' },
  { code: 'CORNILESCU', source: 'thiagobodruk', file: 'ro_cornilescu.json', label: 'Cornilescu (Romanian)', language: 'Romanian' },
  { code: 'VIETNAMESE', source: 'thiagobodruk', file: 'vi_vietnamese.json', label: 'Vietnamese Bible', language: 'Vietnamese' },
  { code: 'SVD', source: 'thiagobodruk', file: 'ar_svd.json', label: 'Arabic Bible (SVD)', language: 'Arabic' },
  { code: 'FINNISH', source: 'thiagobodruk', file: 'fi_finnish.json', label: 'Finnish Bible', language: 'Finnish' },
  { code: 'PR', source: 'thiagobodruk', file: 'fi_pr.json', label: 'Pyhä Raamattu', language: 'Finnish' },
  { code: 'ESPERANTO', source: 'thiagobodruk', file: 'eo_esperanto.json', label: 'Esperanto', language: 'Esperanto' },
];

export const DEFAULT_BIBLE_TRANSLATIONS = BIBLE_TRANSLATION_CATALOG;
